# Generated by Django 5.2.6 on 2026-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=150)),
                ('dept', models.CharField(verbose_name=50)),
                ('salary', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
    ]
