# Generated by Django 5.2.6 on 2026-03-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='c',
            new_name='image',
        ),
    ]
